### ISSUE TITLE
cpp.cuda.train.synthetic.jsonl  issue

### ISSUE THREAD

**Issue by jinz2014** [tehranixyz/CodeRosetta#1]
Hello

"cpp.cuda.train.synthetic.jsonl" contains ~6000 lines, right ? But a collection of 243,008 C++ and CUDA source code files in the paper. Thanks for clarifying this.

**Comment by tehranixyz** [comment]
Hello,

Thank you for reaching out.

The `cpp.cuda.train.synthetic.jsonl` is the synthetic dataset and intended for fine-tuning purposes.

We had been waiting for permission from the BabelTower authors to upload the training sets, as the data originates from them. I’ve just received their authorization, and the files are now available.
