### ISSUE TITLE
cuda.mono.train.tok issue

### ISSUE THREAD

**Issue by jinz2014** [tehranixyz/CodeRosetta#3]
Hello
Is it right the file cuda.mono.train.tok contains 135972 lines ? It is different from the number of Cuda files mentioned in the paper. Thanks for clarifying this.

**Comment by tehranixyz** [comment]
Hello
This is the raw training file. After loading the file, several filter functions are applied to remove noisy samples in the file. This will effectively reduce the size of CUDA training samples.
