### ISSUE TITLE
NCCL timeout 

### ISSUE THREAD

**Issue by jinz2014** [tehranixyz/CodeRosetta#4]
Hello

Could the results of the following steps be saved for reuse ?  It is possible that there is NCCL timeout (600000 ms) in the next phase (count pairs); I am not sure if you encountered the timeout issue and how you set the timeout value.  Each step takes a while to finish. 

accelerate launch --num_processes=4 main.py --langs cpp cuda --train_mode mlm aer bt ft eval --dataset_format tok

Pre-processing sequences       ████████████████████████████████████████████████████ 0        /       
Tokenize words                 ████████████████████████████████████████████████████ 1304921  /  1304921

**Comment by tehranixyz** [comment]
Hello,

Tokenizer training does not support multi-GPU at the moment, I think the workout is to use one GPU. Once the tokenizer is trained it will be saved and used the next time.
