### ISSUE TITLE
tree_sitter_c may be required

### ISSUE THREAD

**Issue by jinz2014** [tehranixyz/CodeRosetta#5]
codebleu/utils.py", line 153, in get_tree_sitter_language
    import tree_sitter_c
ModuleNotFoundError: No module named 'tree_sitter_c'

**Comment by jinz2014** [comment]
tree_sitter_language = get_tree_sitter_language(lang)
  
File "utils.py", line 155, in get_tree_sitter_language
    return Language(tree_sitter_c.language())
TypeError: an integer is required

**Comment by jinz2014** [comment]
In addition, could you confirm if installing the tree-sitter 0.23.2 could be a solution to (TypeError: an integer is required)?

Name: tree-sitter
Version: 0.23.2

**Comment by tehranixyz** [comment]
It seems like there are some changes in the Tree-Sitter and CodeBLEU metric.
I'll check and see if it is possible to resolve this issue. 
For now, feel free to remove the CodeBLEU metric to avoid this issue.
