### ISSUE TITLE
tag question

### ISSUE THREAD

**Issue by jinz2014** [tehranixyz/CodeRosetta#6]
Hello

The values in the tags are 0, 1, or 2 in the file "cuda.mono.train.aer.jsonl". Are they AST Entity Recognition Tags in appendix D.2 ? 
It is not clear there are only three tag types in jsonl but the tag IDs are odd values from 1 to 15.

**Comment by tehranixyz** [comment]
Thank you for bringing this to our attention.
The files you mentioned were an older version of the data that had been uploaded.
We have now uploaded the updated files.

**Comment by jinz2014** [comment]
I am not sure about the tag ID for "bottom_data".  For example,

{"tokens":["__global__","void","MaxPool2d","(","float","*","bottom_data",",","const","int","height"," ... }

The tag IDs for the above tokes are 0,7,3,0,7,13,13,0,15,7,1

So the tag ID of 'bottom_data' is 13 while it is 1 for 'height'.
